# This workflow will upload the ABD-model Python package to PyPI when a release is created.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by separate terms of service, privacy policy, and support documentation.

name: Upload ABD-model Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install build tools and validators
        run: |
          python -m pip install --upgrade pip
          pip install build check-manifest twine

      - name: Validate MANIFEST and metadata
        run: |
          check-manifest
          python setup.py sdist bdist_wheel
          twine check dist/*

      - name: Clean dist directory
        run: rm -rf dist/*

      - name: Build release distributions
        run: python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      id-token: write  # Required for trusted publishing

    environment:
      name: pypi
      # Optional: Uncomment if your release tags follow version format
      # url: https://pypi.org/project/ABD-model/${{ github.event.release.name }}

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish ABD-model ${{ github.event.release.name }} to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
