name: Python Package using Conda

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        miniconda-version: "latest"
        activate-environment: test-env

    - name: Create Conda environment
      run: |
        if [ -f "environment.yml" ]; then
          conda env create -f environment.yml -n test-env
        else
          echo "No environment.yml found, creating default environment"
          conda create -n test-env python=${{ matrix.python-version }} numpy pandas -y
        fi

    - name: Activate environment and install dependencies
      run: |
        conda activate test-env
        conda install --quiet --yes pytest pytest-cov flake8
        pip install -e .

    - name: List installed packages (debugging)
      run: |
        conda list
        pip list

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: success()
